export default{
  
  "login": "Manjunath-N-K",
  "id": 65903988,
  "node_id": "MDQ6VXNlcjY1OTAzOTg4",
  "avatar_url": "https://avatars.githubusercontent.com/u/65903988?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Manjunath-N-K",
  "html_url": "https://github.com/Manjunath-N-K",
  "followers_url": "https://api.github.com/users/Manjunath-N-K/followers",
  "following_url": "https://api.github.com/users/Manjunath-N-K/following{/other_user}",
  "gists_url": "https://api.github.com/users/Manjunath-N-K/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Manjunath-N-K/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Manjunath-N-K/subscriptions",
  "organizations_url": "https://api.github.com/users/Manjunath-N-K/orgs",
  "repos_url": "https://api.github.com/users/Manjunath-N-K/repos",
  "events_url": "https://api.github.com/users/Manjunath-N-K/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Manjunath-N-K/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Manju",
  "company": null,
  "blog": "",
  "location": "Bangalore Karnataka",
  "email": null,
  "hireable": null,
  "bio": "My Bio",
  "twitter_username": null,
  "public_repos": 18,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-05-25T12:52:57Z",
  "updated_at": "2022-03-03T07:30:24Z"
  
}
